### ISSUE TITLE
Possible to release 4.2.3 version?

### ISSUE THREAD

**Issue by guergana** [DataValues/Geo#204]
Thanks for speeding up the release of 4.3.0. When trying to update the version in [mediawiki-vendor](https://gerrit.wikimedia.org/r/c/mediawiki/vendor/), I've realized our PHP version is 7.2 and doesn't meet the requirements for version `4.3.0` of DataValues/Geo package. 

Is it possible to make a release 4.2.3 that only includes [PR 200](https://github.com/DataValues/Geo/pull/200) and doesn't update the version? Thank you.

**Comment by JeroenDeDauw** [comment]
Pull requests into `4.2.x` are welcome
