### ISSUE TITLE
Fix PHP 8.1 deprecation warnings

### ISSUE THREAD

**Issue by JeroenDeDauw** [DataValues/Geo#214]
> Using PHP 8.1.6
> PHP Deprecated:  DataValues\Geo\Values\LatLongValue implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /home/runner/work/Maps/Maps/mediawiki/vendor/data-values/geo/src/Values/LatLongValue.php on line 22

**Comment by JeroenDeDauw** [comment]
Needs to be fixed in base library: https://github.com/DataValues/DataValues/issues/72

**Comment by reedy** [comment]
Probably can be closed
