### ISSUE TITLE
Latitude +/- 360?

### ISSUE THREAD

**Issue by sbiribizio** [DataValues/Geo#68]
In file called LatLongValue.php the latitude is defined in the range [-360, 360]. 
This can lead to an error.
Using degrees, the latitude must be in the range [-90, 90], conventionally from South Pole (-90), Equator (0), to North Pole (90).

**Comment by filbertkm** [comment]
@sbiribizio for some other globes like Mars, latitude ranges from 0 to 360

http://planetarynames.wr.usgs.gov/TargetCoordinates

**Comment by JeroenDeDauw** [comment]
@sbiribizio As @filbertkm pointed out, we cannot restrict the value more in this class as far as we know. There might however be other ways to restrict the value for your use case. Which begs the question what your use case is. Are you using this library via Wikidata/Wikibase? Are you using some other MediaWiki extension such as Maps or Semantic MediaWiki? Are you using the library as part of some other software?

**Comment by thiemowmde** [comment]
In case you are asking this question for what happens on wikidata.org, the validators for wikidata.org are defined in https://github.com/wikimedia/mediawiki-extensions-Wikibase/blob/master/repo/includes/ValidatorBuilders.php#L267. We can add more restrictions there. This should be discussed in a ticket on http://phabricator.wikimedia.org then.
